import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Eye, Plus, RefreshCw, Save, Search, Trash2 } from 'lucide-react';
import usePageTitle from '../hooks/usePageTitle';
import { compareQuestionDraft, normalizeEditorQuestion, validateQuestionDraft } from '../../shared/questionInspection.js';

const EMPTY={question:'',vignette:'',type:'single',difficulty:'medium',options:[],acceptedShortAnswers:[],explanation:'',clinicalPearl:'',referenceBook:'',imageUrl:'',isPublished:true};
export default function AdminContentPage(){
 usePageTitle('Xưởng kiểm định câu hỏi'); const [data,setData]=useState({questions:[],pagination:{page:1,pages:1,total:0},catalog:{subjects:[],decks:[]}}),[q,setQ]=useState(new URLSearchParams(location.search).get('q')||''),[subject,setSubject]=useState(''),[deck,setDeck]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState(null),[draft,setDraft]=useState(EMPTY),[tab,setTab]=useState('edit'),[inspect,setInspect]=useState(false),[history,setHistory]=useState([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=async()=>{setBusy(true);try{const p=new URLSearchParams({page,limit:30});if(q)p.set('q',q);if(subject)p.set('subjectId',subject);if(deck)p.set('deckPath',deck);const r=await fetch(`/api/admin/content?${p}`,{credentials:'include'}),j=await r.json();if(!r.ok)throw Error(j.message);setData(j);const n=j.questions.find(x=>x.id===selected?.id)||j.questions[0]||null;setSelected(n);setDraft(n?normalizeEditorQuestion(n):EMPTY)}catch(e){setMessage(e.message)}finally{setBusy(false)}};
 useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t);/* load is intentionally driven by filters */},[q,subject,deck,page]); // eslint-disable-line react-hooks/exhaustive-deps
 const comparison=useMemo(()=>selected?compareQuestionDraft(selected,draft):null,[selected,draft]), validation=useMemo(()=>validateQuestionDraft(draft),[draft]);
 const setField=(k,v)=>setDraft(x=>({...x,[k]:v})), choose=x=>{setSelected(x);setDraft(normalizeEditorQuestion(x));setInspect(false);setMessage('')};
 const inspectNow=async()=>{setInspect(!inspect);if(selected){const r=await fetch(`/api/admin/content?resource=revisions&questionId=${selected.id}`,{credentials:'include'}),j=await r.json();setHistory(j.revisions||[])}};
 const publish=async mode=>{if(!validation.valid)return setMessage('Cần sửa lỗi kiểm tra trước khi xuất bản.');setBusy(true);try{const r=await fetch('/api/admin/content',{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected.id,expectedUpdatedAt:selected.updatedAt,mode,draft})}),j=await r.json();if(!r.ok)throw Error(j.message);setMessage(j.message);await load()}catch(e){setMessage(e.message)}finally{setBusy(false)}};
 const restore=async revisionId=>{setBusy(true);const r=await fetch('/api/admin/content?resource=revisions',{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({revisionId})}),j=await r.json();setMessage(j.message);await load();setBusy(false)};
 const decks=data.catalog.decks.filter(x=>!subject||x.subjectId===subject);
 return <div className="min-h-[100dvh] p-3 sm:p-6 text-slate-800 dark:text-slate-200"><div className="max-w-[1600px] mx-auto space-y-4"><header className="admin-shell"><h1 className="text-2xl font-black">Xưởng kiểm định câu hỏi</h1><p className="text-sm text-slate-500">Sửa đúng một câu, xem trước và kiểm tra thay đổi trước khi xuất bản.</p></header>
 <section className="admin-shell grid md:grid-cols-3 gap-3"><label className="relative"><Search className="absolute w-4 left-3 top-3"/><input className="admin-input pl-9" value={q} onChange={e=>setQ(e.target.value)} placeholder="ID hoặc nội dung câu"/></label><select className="admin-input" value={subject} onChange={e=>{setSubject(e.target.value);setDeck('')}}><option value="">Tất cả môn</option>{data.catalog.subjects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="admin-input" value={deck} onChange={e=>setDeck(e.target.value)}><option value="">Tất cả đề</option>{decks.map(x=><option key={x.path} value={x.path}>{x.name}</option>)}</select></section>{message&&<div className="rounded-xl bg-amber-50 border border-amber-200 p-3 text-sm">{message}</div>}
 <div className="grid lg:grid-cols-[330px_1fr] gap-4 items-start"><aside className="admin-shell max-h-[78dvh] overflow-auto lg:sticky lg:top-3"><div className="flex justify-between pb-3"><b>{data.pagination.total} câu</b><button onClick={load}><RefreshCw className={`w-4 ${busy?'animate-spin':''}`}/></button></div>{data.questions.map(x=><button key={x.id} onClick={()=>choose(x)} className={`block w-full text-left p-3 border-t ${selected?.id===x.id?'bg-teal-50 dark:bg-teal-950/30':''}`}><span className="font-mono text-xs text-teal-600">{x.publicId}</span><p className="font-bold text-sm line-clamp-2">{x.question}</p><small>{x.deckName}</small></button>)}<div className="flex justify-between pt-3"><button disabled={page<=1} onClick={()=>setPage(page-1)}>← Trước</button><span>{page}/{data.pagination.pages}</span><button disabled={page>=data.pagination.pages} onClick={()=>setPage(page+1)}>Sau →</button></div></aside>
 <main className="admin-shell">{!selected?<p>Chọn một câu hỏi.</p>:<><div className="flex gap-2 lg:hidden mb-4">{[['edit','Sửa'],['preview','Xem trước'],['inspect','Kiểm tra']].map(([k,v])=><button key={k} onClick={()=>setTab(k)} className={`px-3 py-2 rounded-xl ${tab===k?'bg-teal-500 text-white':'bg-slate-100'}`}>{v}</button>)}</div><div className="grid lg:grid-cols-2 gap-5"><section className={`${tab!=='edit'?'hidden lg:block':''} space-y-3`}><div><b className="font-mono text-teal-600">{selected.publicId}</b><p className="text-xs text-slate-500">{selected.subjectName} · {selected.deckName}</p></div><label className="block"><span className="admin-label">Câu hỏi</span><textarea className="admin-input" rows="4" value={draft.question} onChange={e=>setField('question',e.target.value)}/></label><label className="block"><span className="admin-label">Dữ kiện</span><textarea className="admin-input" rows="3" value={draft.vignette} onChange={e=>setField('vignette',e.target.value)}/></label><div className="flex gap-2"><button onClick={()=>setField('type','single')} className="px-3 py-2 rounded-xl bg-teal-100">Trắc nghiệm</button><button onClick={()=>setField('type','short_answer')} className="px-3 py-2 rounded-xl bg-slate-100">Trả lời ngắn</button></div>{draft.type==='short_answer'?<textarea className="admin-input" value={draft.acceptedShortAnswers.join('\n')} onChange={e=>setField('acceptedShortAnswers',e.target.value.split('\n'))} placeholder="Mỗi dòng một đáp án được chấp nhận"/>:<div className="space-y-2"><span className="admin-label">Bản đồ đáp án — tích đáp án đúng</span>{draft.options.map((o,i)=><div key={i} className="flex gap-2"><input type="checkbox" checked={o.isCorrect} onChange={e=>setField('options',draft.options.map((v,n)=>n===i?{...v,isCorrect:e.target.checked}:v))}/><input className="admin-input" value={o.text} onChange={e=>setField('options',draft.options.map((v,n)=>n===i?{...v,text:e.target.value}:v))}/><button onClick={()=>setField('options',draft.options.filter((_,n)=>n!==i))}><Trash2 className="w-4"/></button></div>)}<button onClick={()=>setField('options',[...draft.options,{id:'',text:'',isCorrect:false}])} className="text-sm text-teal-600 flex gap-1"><Plus className="w-4"/>Thêm lựa chọn</button></div>}<details><summary className="font-bold cursor-pointer">Giải thích, nguồn và ảnh</summary><div className="space-y-2 mt-2"><textarea className="admin-input" value={draft.explanation} onChange={e=>setField('explanation',e.target.value)} placeholder="Giải thích"/><textarea className="admin-input" value={draft.referenceBook} onChange={e=>setField('referenceBook',e.target.value)} placeholder="Nguồn"/><input className="admin-input" value={draft.imageUrl} onChange={e=>setField('imageUrl',e.target.value)} placeholder="Link ảnh https://"/></div></details></section>
 <section className={`${tab!=='preview'?'hidden lg:block':''} rounded-2xl border p-5 bg-slate-50 dark:bg-white/5`}><div className="flex gap-2 mb-4"><Eye className="w-4"/><b>Xem trước</b></div><p className="text-lg font-black">{draft.question||'Chưa có nội dung'}</p><p>{draft.vignette}</p><div className="space-y-2 mt-4">{draft.options.map((o,i)=><div key={i} className={`p-3 rounded-xl border ${o.isCorrect?'border-emerald-400 bg-emerald-50 text-emerald-800':'bg-white dark:bg-white/5'}`}>{String.fromCharCode(65+i)}. {o.text}</div>)}</div></section></div>
 <section className={`${tab!=='inspect'?'hidden lg:block':''} mt-5 border-t pt-4`}><button onClick={inspectNow} className="flex gap-2 font-bold"><AlertTriangle className="w-4"/>Kiểm tra trước khi xuất bản</button>{inspect&&<div className="grid md:grid-cols-2 gap-4 mt-3"><div>{validation.errors.map(x=><p key={x} className="text-rose-600 text-sm">• {x}</p>)}{validation.warnings.map(x=><p key={x} className="text-amber-600 text-sm">• {x}</p>)}<p className="text-sm mt-2">Thay đổi: {comparison?.changedFields.join(', ')||'không có'} · điểm {comparison?.changeScore}</p><div className="flex gap-2 mt-3"><button disabled={busy||!comparison?.hasChanges} onClick={()=>publish('edit')} className="px-4 py-2 rounded-xl bg-teal-500 text-white font-bold flex gap-2"><Save className="w-4"/>Cập nhật</button>{comparison?.suggestedMode==='replace'&&<button onClick={()=>publish('replace')} className="px-4 py-2 rounded-xl bg-amber-500 text-white font-bold">Thay câu mới</button>}</div></div><div><b>Lịch sử</b>{history.map(x=><div key={x._id} className="flex justify-between border-b py-2 text-sm"><span>Bản {x.revision} · {x.action}</span><button className="text-teal-600" onClick={()=>restore(x._id)}>Khôi phục</button></div>)}</div></div>}</section></>}</main></div></div></div>;
}
